server:
  port: 80
  servlet:
    context-path: /satan-admin
logging:
  path: C:/LOGS/Satan-Admin
  level:
    root: info
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: jdbc:mysql://localhost:3306/satan-admin?characterEncoding=utf8&serverTimezone=GMT%2b8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialization-mode: embedded
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: update
  profiles:
    active: pro
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non-null
    serialization:
      indent-output: true
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    parser:
      allow-unquoted-control-chars: true
      allow-single-quotes: true
app:
  enable-safer: true
  log-request-info: true
  allow-local-cross-domain: false
